config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products
  root 'store#index', as: 'store'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, presence: true
  validates :title, uniqueness: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :image_url, allow_blank: true, format: {
      with: %r{\.(gif|jpg|png)\Z}i,
      message: 'Only GIF, JPG or PNG'
  }

  def self.latest
    Product.order(:updated_at).last
  end

  private
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'line items are exist')
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url }
      format.json { head :no_content }
    end
  end

  private
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern

  private
  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  include CurrentCart
  before_action :set_cart, only: [:create]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_url }
        format.js   { @current_item = @line_item }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    if @line_item.quantity == 1
      @line_item.destroy
    else
      @line_item.quantity -= 1
      @line_item.save!
    end
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  include CurrentCart
  before_action :set_cart

  def index
    @products = Product.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes['style'] = 'display: none'
    end
    content_tag('div', attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.slim
- unless cart.line_items.empty?
  h2 Your Cart

  ul == render cart.line_items

  h3 Total
  = number_to_currency(cart.total_price)

  = button_to 'Empty cart', cart, method: :delete, data: { confirm: 'Are you sure?' }

  = link_to 'Edit', edit_cart_path(cart)
  = link_to 'Back', carts_path

app/views/carts/_form.html.slim
= form_for @cart do |f|
  - if @cart.errors.any?
    div#error_explanation
      h2 = pluralize(@cart.errors.count, 'error')
      | prohibited this cart from being saved:

      ul
        - @cart.errors.full_messages.each do |message|
          li = message
  div.actions
    = f.submit

app/views/carts/edit.html.slim
h1 Editing cart

== render 'form'

= link_to 'Show', @cart
= link_to 'Back', carts_path

app/views/carts/index.html.slim
h1 Listing carts

table
  thead
    tr
      th colspan='3'
  tbody
    - @carts.each do |cart|
      tr
        td = link_to 'Show', cart
        td = link_to 'Edit', edit_cart_path(cart)
        td = link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New cart', new_cart_path

app/views/carts/new.html.slim
h1 New cart

== render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.slim
- if notice
  p#notice = notice

== render @cart

app/views/layouts/application.html.slim
doctype html
html
  head
    title Nuos Shop
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    div#banner
      = @page_title || 'Bookshelf'
    div#columns
      div#side
        ul
          = hidden_div_if(@cart.line_items.empty?, id: 'cart') do
            == render @cart
          li
            a href='/' Home
      div#main
        = yield

app/views/line_items/_form.html.slim
= form_for @line_item do |f|
  - if @line_item.errors.any?
    div#error_explanation
      h2 = pluralize(@line_item.errors.count, 'error')
      | prohibited this line item from being saved:

      ul
        - @line_item.errors.full_messages.each do |message|
          li = message

  div.field
    = f.label :product_id
    = f.text_field :product_id

  div.field
    = f.label :cart_id
    = f.text_field :cart_id

  div.actions
    = f.submit

app/views/line_items/_line_item.html.slim
- if line_item == @current_item
  li#current_item
- else
  li
= line_item.quantity
| ×
= line_item.product.title
= number_to_currency(line_item.total_price)
= button_to 'delete', line_item, method: :delete

app/views/line_items/create.js.erb
$('#cart').html("<%= escape_javascript render(@cart) %>");

if ($('#cart li').length == 1) { $('#cart').show('blind', 1000); }

$('#current_item').css({ 'background-color' : '#88ff88' })
                  .animate({ 'background-color' : '#114411' }, 1000);

app/views/line_items/edit.html.slim
h1 Editing line item

= render 'form'

= link_to 'Show', @line_item
= link_to 'Back', line_items_path

app/views/line_items/index.html.slim
h1 Listing line items

table
  thead
    tr
      th Product
      th Car
      th colspan='3'
  tbody
    - @line_items.each do |line_item|
      tr
        td = line_item.product
        td = line_item.cart
        td = link_to 'Show', line_item
        td = link_to 'Edit', edit_line_item_path(line_item)
        td = link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New line item', new_line_item_path

app/views/line_items/new.html.slim
h1 New line item

== render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.slim
p#notice = notice

p
  strong Product:
  = @line_item.product

p
  strong Cart:
  = @line_item.cart

= link_to 'Edit', edit_line_item_path(@line_item)
= link_to 'Back', line_items_path

app/views/products/_form.html.slim
= form_for @product do |f|
  - if @product.errors.any?
    div#error_explanation
      h2 = pluralize(@product.errors.count, 'error')
      | prohibited this product from being saved:

      ul
        - @product.errors.full_messages.each do |message|
          li = message

  div.field
    = f.label :title
    = f.text_field :title

  div.field
    = f.label :description
    = f.text_area :description, rows: 6

  div.field
    = f.label :image_url
    = f.text_field :image_url

  div.field
    = f.label :price
    = f.text_field :price

  div.actions
    = f.submit

app/views/products/edit.html.slim
h1 Editing product

= render 'form'

= link_to 'Show', @product
= link_to 'Back', products_path

app/views/products/index.html.slim
h1 Listing products

table
  thead
    tr
      th Title
      th Description
      th Image url
      th Price
      th colspan="3"
  tbody
    - @products.each do |product|
      tr
        td = product.title
        td = truncate(strip_tags(product.description), length: 80)
        td = product.image_url
        td = number_to_currency(product.price)
        td = link_to 'Show', product
        td = link_to 'Edit', edit_product_path(product)
        td = link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Product', new_product_path

app/views/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', products_path

app/views/products/show.html.slim
p#notice = notice

p
  strong Title:
  = @product.title
p
  strong Description:
  = @product.description
p
  strong Image url:
  = @product.image_url
p
  strong Price:
  = number_to_currency(@product.price)

= link_to 'Edit', edit_product_path(@product)
= link_to 'Back', products_path

app/views/store/index.html.slim
- if notice
  p#notice
    = notice

h1 Your catalog
- cache ['store', Product.latest] do
  - @products.each do |product|
    - cache ['entry', product] do
      = image_tag(product.image_url)
      h3 = product.title
      = product.description
      = number_to_currency(product.price)
      = button_to 'Add to Cart', line_items_path(product_id: product), remote: true